name: test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        img:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macOS-latest
          - macOS-14
        rust:
          - stable
        include:
          - img: ubuntu-latest
            rust: nightly
          - img: macOS-latest
            rust: nightly
        
    runs-on: ${{ matrix.img }}

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo test --verbose --all -- --test-threads=1
